import { Injectable } from '@nestjs/common';
import * as jwt from 'jsonwebtoken';
import { addHours } from 'date-fns';

import { DatabaseService } from 'src/core';
import {
  ChatCreateInputDto,
  ChatUpdateInputDto,
  InviteTokenInputDto,
  InviteTokenOutputDto,
} from './dtos';
import { ChatListParams } from './params';
import { isTokenExpired, UserChatRole, UserType } from '@circle-vibe/shared';
import { JWT_TOKEN_SECRET } from 'src/configuration';
import { ChatParticipant } from '@prisma/client';

@Injectable()
export class ChatService {
  defaultUsersLimit = 100;

  constructor(private databaseService: DatabaseService) {}

  async findById(chatId: number) {
    return this.databaseService.chat.findUnique({
      where: {
        id: chatId,
      },
    });
  }

  /**
   * Creates a new chat in the database.
   *
   * @param createChatDto - The data to be used to create the chat.
   * @returns The newly created chat.
   *
   * The `usersLimit` field is optional and if not provided, the default value of
   * `this.defaultUsersLimit` (set to 100) will be used.
   *
   * The `readableName` field is autogenerated from the `name` field.
   *
   * The `lastMessageId` and `lastMessage` fields are autogenerated and set to
   * `undefined` and `{}`, respectively.
   */
  async create(
    createChatDto: ChatCreateInputDto,
    options?: {
      isSavedMessages?: boolean;
    },
  ) {
    const payload: ChatCreateInputDto = {
      ...createChatDto,
      usersLimit: (createChatDto?.usersLimit ??
        this.defaultUsersLimit) as number,
    };

    const autogeneratedFields = {
      lastMessageId: undefined,
      lastMessage: {},
      readableName: this.#composeReadableName(createChatDto.name),
      isSavedMessages: options?.isSavedMessages ?? false,
    };

    const chat = await this.databaseService.chat.create({
      data: {
        ...payload,
        ...autogeneratedFields,
      },
    });

    return chat;
  }

  /**
   * Finds a chat by its readable name.
   *
   * @param readableName - The readable name of the chat to be found.
   * @returns The found chat.
   *
   * @throws If no chat with the given readable name is found in the database,
   *         an error is thrown.
   */
  async getByReadableName(readableName: string) {
    return this.databaseService.chat.findUnique({
      where: {
        readableName,
      },
    });
  }

  /**
   * Updates a chat in the database.
   *
   * @param chatId - The id of the chat to be updated.
   * @param updateChatDto - The data to be used to update the chat.
   *
   * @returns The updated chat.
   */
  async update(chatId: number, updateChatDto: ChatUpdateInputDto) {
    return this.databaseService.chat.update({
      where: {
        id: chatId,
      },
      data: {
        ...updateChatDto,
      },
    });
  }

  async getById(chatId: number) {
    return await this.databaseService.chat.findUnique({
      where: {
        id: chatId,
      },
    });
  }

  async getAll(params: ChatListParams) {
    const chats = await this.databaseService.chat.findMany({
      where: {
        // ...params,
      },
    });

    const chatIds = chats.map(({ id }) => Number(id));
    const lastMessages = await this.databaseService.message.findMany({
      where: {
        chatId: {
          in: chatIds,
        },
      },
      include: {
        files: true,
        sender: {
          include: {
            // @ts-ignore
            user: true,
          },
        },
      },
      take: 1,
      distinct: ['chatId'],
      orderBy: {
        createdAt: 'desc',
      },
    });

    return chats.map((chat) => {
      const lastMessage = lastMessages.find(
        (message) => message.chatId === chat.id,
      );

      return {
        ...chat,
        empty: !lastMessage,
        lastMessageId: lastMessage?.id,
        lastMessage,
      };
    });
  }

  async softDelete(chatId: number) {
    return this.databaseService.chat.update({
      where: {
        id: chatId,
      },
      data: {
        removed: true,
        lastMessage: {},
        lastMessageId: undefined,
        empty: true,
        updatedAt: new Date(),
        isActive: false,
        hidden: true,
      },
    });
  }

  async delete(chatId: number) {
    return this.databaseService.chat.delete({
      where: {
        id: chatId,
      },
    });
  }

  async getLastMessage(chatId: number) {
    return this.databaseService.message.findFirst({
      where: {
        chatId,
      },
      orderBy: {
        updatedAt: 'desc',
      },
    });
  }

  #composeReadableName(name: string): string {
    const spaceOrSpecialSymbolRegex = /[\s\W]/g;

    return [name.split(spaceOrSpecialSymbolRegex), Date.now()]
      .join('-')
      .toLowerCase();
  }

  async generateInviteToken(
    chatId: number,
    targetUserId: number,
    fromChatParticipantId: number,
  ) {
    const user = await this.databaseService.user.findUnique({
      where: {
        id: targetUserId,
      },
    });

    const expirationHours = user?.type === UserType.PRIVATE ? 1 : 2;
    const payload: InviteTokenInputDto = {
      chatId,
      targetUserId,
      role: UserChatRole.MEMBER,
      fromChatParticipantId,
    };

    return {
      token: jwt.sign(payload, JWT_TOKEN_SECRET, {
        expiresIn: `${expirationHours}h`,
      }),
      expirationDate: addHours(new Date(), expirationHours),
    };
  }

  async validateInviteToken(token: string): Promise<InviteTokenOutputDto> {
    const payload = jwt.verify(token, JWT_TOKEN_SECRET) as jwt.JwtPayload &
      InviteTokenInputDto;
    const isExpired =
      Boolean(payload?.exp) && isTokenExpired(Number(payload?.exp));
    const isValid =
      Boolean(payload?.chatId) &&
      Boolean(payload?.targetUserId) &&
      Boolean(payload?.fromChatParticipantId) &&
      !isExpired;
    const data: InviteTokenInputDto = {
      chatId: payload?.chatId,
      targetUserId: payload?.targetUserId,
      role: payload?.role,
      fromChatParticipantId: payload?.fromChatParticipantId,
    };

    return {
      data,
      isExpired,
      isValid,
    };
  }

  isChatParticipantExist(
    chatId: number,
    userId: number,
  ): Promise<ChatParticipant | null> {
    return this.databaseService.chatParticipant.findFirst({
      where: {
        chatId,
        userId,
      },
    });
  }
}
