import { Injectable } from '@nestjs/common';

import { DatabaseService } from 'src/core';
import { ChatCreateInputDto, ChatUpdateInputDto } from './dtos';
import { get } from 'http';
import { ChatListParams } from './params';
import { Message } from '@prisma/client';

@Injectable()
export class ChatService {
  defaultUsersLimit = 100;

  constructor(private databaseService: DatabaseService) {}

  async findById(chatId: number) {
    return this.databaseService.chat.findUnique({
      where: {
        id: chatId,
      },
    });
  }

  /**
   * Creates a new chat in the database.
   *
   * @param createChatDto - The data to be used to create the chat.
   * @returns The newly created chat.
   *
   * The `usersLimit` field is optional and if not provided, the default value of
   * `this.defaultUsersLimit` (set to 100) will be used.
   *
   * The `readableName` field is autogenerated from the `name` field.
   *
   * The `lastMessageId` and `lastMessage` fields are autogenerated and set to
   * `undefined` and `{}`, respectively.
   */
  async create(createChatDto: ChatCreateInputDto) {
    const payload: ChatCreateInputDto = {
      ...createChatDto,
      usersLimit: (createChatDto?.usersLimit ??
        this.defaultUsersLimit) as number,
    };

    const autogeneratedFields = {
      lastMessageId: undefined,
      lastMessage: {},
      readableName: this.#composeReadableName(createChatDto.name),
    };

    const chat = await this.databaseService.chat.create({
      data: {
        ...payload,
        ...autogeneratedFields,
      },
    });

    return chat;
  }

  /**
   * Finds a chat by its readable name.
   *
   * @param readableName - The readable name of the chat to be found.
   * @returns The found chat.
   *
   * @throws If no chat with the given readable name is found in the database,
   *         an error is thrown.
   */
  async getByReadableName(readableName: string) {
    return this.databaseService.chat.findUnique({
      where: {
        readableName,
      },
    });
  }

  /**
   * Updates a chat in the database.
   *
   * @param chatId - The id of the chat to be updated.
   * @param updateChatDto - The data to be used to update the chat.
   *
   * @returns The updated chat.
   */
  async update(chatId: number, updateChatDto: ChatUpdateInputDto) {
    return this.databaseService.chat.update({
      where: {
        id: chatId,
      },
      data: {
        ...updateChatDto,
      },
    });
  }

  async getById(chatId: number) {
    return await this.databaseService.chat.findUnique({
      where: {
        id: chatId,
      },
    });
  }

  async getAll(params: ChatListParams) {
    const chats = await this.databaseService.chat.findMany({
      where: {
        // ...params,
      },
    });

    const chatIds = chats.map(({ id }) => Number(id));

    const lastMessages = await this.databaseService.$queryRawUnsafe<Message[]>(`
      SELECT DISTINCT ON ("chatId") *
      FROM "Message" m
      WHERE m."createdAt" = (
        SELECT MAX(m2."createdAt")
        FROM "Message" m2
        WHERE m2."chatId" = m."chatId"
      )
      AND m."chatId" IN (${chatIds});
    `, chatIds);

    return chats.map((chat) => {
      const lastMessage = lastMessages.find(
        (message) => message.chatId === chat.id,
      );

      return {
      ...chat,
      empty: !lastMessage,
      lastMessageId: lastMessage?.id,
      lastMessage,
    }});
  }

  async softDelete(chatId: number) {
    return this.databaseService.chat.update({
      where: {
        id: chatId,
      },
      data: {
        removed: true,
        lastMessage: {},
        lastMessageId: undefined,
        empty: true,
        updatedAt: new Date(),
        isActive: false,
        hidden: true,
      },
    });
  }

  async delete(chatId: number) {
    return this.databaseService.chat.delete({
      where: {
        id: chatId,
      },
    });
  }

  async getLastMessage(chatId: number) {
    return this.databaseService.message.findFirst({
      where: {
        chatId,
      },
      orderBy: {
        updatedAt: 'desc',
      },
    });
  }

  #composeReadableName(name: string): string {
    const spaceOrSpecialSymbolRegex = /[\s\W]/g;

    return name.split(spaceOrSpecialSymbolRegex).join('-').toLowerCase();
  }
}
