import { BadRequestException, Injectable } from '@nestjs/common';
import * as jwt from 'jsonwebtoken';
import { addHours } from 'date-fns';

import { FileService } from 'src/core/services';
import { DatabaseService } from 'src/core';
import { ChatCreateInputDto, ChatUpdateInputDto, InviteTokenInputDto, InviteTokenOutputDto } from './dtos';
import { ChatListParams, SearchUserForInvitationInputDto } from './params';
import { Chat, isTokenExpired, PaginatedResponse, UserChatRole, UserType } from '@circle-vibe/shared';
import { JWT_TOKEN_SECRET } from 'src/configuration';
import { ChatParticipant, ChatType, MessageFile, Prisma, User } from '@prisma/client';

@Injectable()
export class ChatService {
  defaultUsersLimit = 100;

  constructor(
    private databaseService: DatabaseService,
    private fileService: FileService,
  ) {}

  async findById(chatId: number) {
    return this.databaseService.chat.findUnique({
      where: {
        id: chatId,
      },
    });
  }

  /**
   * Creates a new chat in the database.
   *
   * @param createChatDto - The data to be used to create the chat.
   * @returns The newly created chat.
   *
   * The `usersLimit` field is optional and if not provided, the default value of
   * `this.defaultUsersLimit` (set to 100) will be used.
   *
   * The `readableName` field is autogenerated from the `name` field.
   *
   * The `lastMessageId` and `lastMessage` fields are autogenerated and set to
   * `undefined` and `{}`, respectively.
   */
  async create(
    createChatDto: ChatCreateInputDto,
    options?: {
      isSavedMessages?: boolean;
    },
  ) {
    const payload: ChatCreateInputDto = {
      ...createChatDto,
      usersLimit: createChatDto?.usersLimit ?? this.defaultUsersLimit,
    };

    const autogeneratedFields = {
      lastMessageId: undefined,
      lastMessage: {},
      readableName: this.#composeReadableName(createChatDto.name),
      isSavedMessages: options?.isSavedMessages ?? false,
    };

    const bucket = await this.fileService.createBucket(createChatDto.name, createChatDto.description);

    if (!bucket?.id) {
      throw new BadRequestException('Bucket not found.');
    }

    const chat = await this.databaseService.chat.create({
      data: {
        bucket: bucket.name,
        ...payload,
        ...autogeneratedFields,
      },
    });

    return chat;
  }

  /**
   * Deletes a message from the database.
   *
   * The function first checks if the participant exists and if the participant's
   * chat id matches the chat id of the message.
   *
   * Then it checks if the message exists and if the message's sender id matches
   * the sender id of the participant.
   *
   * If both checks pass, the function deletes the message file and the message
   * itself.
   *
   * @param chatId - The id of the chat in which the message should be deleted.
   * @param messageId - The id of the message to be deleted.
   * @param senderId - The id of the participant who is trying to delete the message.
   *
   * @returns Nothing.
   */
  async deleteChatMessage(chatId: number, messageId: number, userId: number) {
    const participantDto = await this.databaseService.chatParticipant.findFirst({
      where: {
        chatId,
        userId,
      },
    });

    if (!participantDto?.chatId) {
      return;
    }

    const messageDto = await this.databaseService.message.findUnique({
      where: {
        id: messageId,
      },
      select: {
        senderId: true,
        files: true,
      },
    });

    if (!messageDto?.senderId || messageDto?.senderId !== participantDto.id) {
      return;
    }

    await this.databaseService.$queryRawUnsafe(`DELETE FROM "MessageFile" WHERE "messageId" = ${messageId}`);

    this.#deleteFileMessageWithFiles(messageDto.files);

    await this.databaseService.message.delete({
      where: {
        id: messageId,
      },
    });
  }

  /**
   * Finds a chat by its readable name.
   *
   * @param readableName - The readable name of the chat to be found.
   * @returns The found chat.
   *
   * @throws If no chat with the given readable name is found in the database,
   *         an error is thrown.
   */
  async getByReadableName(readableName: string) {
    return this.databaseService.chat.findUnique({
      where: {
        readableName,
      },
    });
  }

  /**
   * Updates a chat in the database.
   *
   * @param chatId - The id of the chat to be updated.
   * @param updateChatDto - The data to be used to update the chat.
   *
   * @returns The updated chat.
   */
  async update(chatId: number, updateChatDto: ChatUpdateInputDto) {
    return this.databaseService.chat.update({
      where: {
        id: chatId,
      },
      data: {
        ...updateChatDto,
      },
    });
  }

  async getById(chatId: number) {
    return await this.databaseService.chat.findUnique({
      where: {
        id: chatId,
      },
    });
  }

  async getChatParticipants(chatId: number) {
    return await this.databaseService.chatParticipant.findMany({
      where: {
        chatId,
      },
      include: {
        user: true,
      },
    });
  }

  async findUserForInvitation(params: SearchUserForInvitationInputDto): Promise<User | null> {
    const { chatParticipantId, chatId, username } = params;
    const personalTargetUserToken = params?.personalTargetUserToken;
    const userFilterByPersonalToken = personalTargetUserToken?.length ? { privateToken: personalTargetUserToken } : {};
    const userFilterByUsername = username?.length ? { username } : {};
    const chatParticipantOfSender = await this.databaseService.chatParticipant.findUnique({
      where: {
        id: chatParticipantId,
      },
    });
    const userToInvite = await this.databaseService.user.findUnique({
      where: {
        ...userFilterByUsername,
        ...userFilterByPersonalToken,
      } as Prisma.UserWhereUniqueInput,
    });

    const userId = userToInvite?.id;

    if (chatParticipantOfSender?.chatRole !== UserChatRole.ADMIN) {
      return null;
    }

    const chatParticipant = await this.databaseService.chatParticipant.findFirst({
      where: {
        chatId,
        userId,
      },
    });

    if (chatParticipant?.id || !userToInvite?.isAllowedToSearch) {
      return null;
    }

    return userToInvite;
  }

  async getAllPaginated(params: ChatListParams): Promise<PaginatedResponse<Chat> | null> {
    const { page, pageSize } = params;
    const skip = (page - 1) * pageSize;
    const take = pageSize;

    const userIdFilterParams = params?.userId?.length
      ? {
          userId: {
            in: params?.userId,
          },
        }
      : {};

    const chatIdsByUser = await this.databaseService.chatParticipant.findMany({
      where: {
        ...userIdFilterParams,
      },
      select: {
        chatId: true,
      },
      distinct: ['chatId'],
    });
    const mappedChatIds = chatIdsByUser.map(({ chatId }) => chatId);
    const filterByName = params?.name?.length
      ? {
          name: {
            contains: params?.name,
          },
        }
      : {};
    const chats = await this.databaseService.chat.findMany({
      where: {
        id: {
          in: mappedChatIds,
        },
        ...filterByName,
        removed: params?.removed ?? false,
        empty: params?.empty,
        type: params?.type ?? ChatType.PRIVATE,
      },
      skip,
    });

    const lastMessages = await this.databaseService.message.findMany({
      where: {
        chatId: {
          in: mappedChatIds,
        },
        threadId: null,
      },
      include: {
        files: true,
        sender: {
          include: {
            user: true,
          },
        },
      },
      take,
      skip,
      distinct: ['chatId'],
      orderBy: {
        createdAt: 'desc',
      },
    });

    const data = chats.map((chat) => {
      const lastMessage = lastMessages.find((message) => message.chatId === chat.id);

      return {
        ...chat,
        empty: lastMessages?.length === 0,
        lastMessageId: lastMessage?.id,
        lastMessage,
      } as unknown as Chat;
    });

    const totalItems = chatIdsByUser.length;

    return {
      data,
      page,
      totalItems,
      pageSize,
      totalPages: Math.ceil(totalItems / pageSize),
    };
  }

  async softDelete(chatId: number) {
    return this.databaseService.chat.update({
      where: {
        id: chatId,
      },
      data: {
        removed: true,
        lastMessage: {},
        lastMessageId: undefined,
        empty: true,
        updatedAt: new Date(),
        isActive: false,
      },
    });
  }

  async delete(chatId: number) {
    const messageIds = await this.databaseService.message.findMany({
      where: {
        chatId,
      },
      select: {
        id: true,
      },
    });

    await this.databaseService.chat.delete({
      where: {
        id: chatId,
      },
    });

    await this.databaseService.chatParticipant.deleteMany({
      where: {
        chatId,
      },
    });

    await this.databaseService.messageFile.deleteMany({
      where: {
        messageId: {
          in: messageIds.length ? messageIds?.map(({ id }) => id) : [],
        },
      },
    });

    await this.databaseService.message.deleteMany({
      where: {
        chatId,
      },
    });
  }

  async getLastMessage(chatId: number) {
    return this.databaseService.message.findFirst({
      where: {
        chatId,
      },
      orderBy: {
        updatedAt: 'desc',
      },
    });
  }

  #composeReadableName(name: string): string {
    const spaceOrSpecialSymbolRegex = /[\s\W]/g;

    return [name.split(spaceOrSpecialSymbolRegex), Date.now()].join('-').toLowerCase();
  }

  async generateInviteToken(chatId: number, targetUserId: number, fromChatParticipantId: number) {
    const user = await this.databaseService.user.findUnique({
      where: {
        id: targetUserId,
      },
    });

    const expirationHours = user?.type === UserType.PRIVATE ? 1 : 2;
    const payload: InviteTokenInputDto = {
      chatId,
      targetUserId,
      role: UserChatRole.MEMBER,
      fromChatParticipantId,
    };

    return {
      token: jwt.sign(payload, JWT_TOKEN_SECRET, {
        expiresIn: `${expirationHours}h`,
      }),
      expirationDate: addHours(new Date(), expirationHours),
    };
  }

  async validateInviteToken(token: string): Promise<InviteTokenOutputDto> {
    const payload = jwt.verify(token, JWT_TOKEN_SECRET) as jwt.JwtPayload & InviteTokenInputDto;
    const isExpired = Boolean(payload?.exp) && isTokenExpired(Number(payload?.exp));
    const isValid = Boolean(payload?.chatId) && Boolean(payload?.targetUserId) && Boolean(payload?.fromChatParticipantId) && !isExpired;
    const data: InviteTokenInputDto = {
      chatId: payload?.chatId,
      targetUserId: payload?.targetUserId,
      role: payload?.role,
      fromChatParticipantId: payload?.fromChatParticipantId,
    };

    return {
      data,
      isExpired,
      isValid,
    };
  }

  isChatParticipantExist(chatId: number, userId: number): Promise<ChatParticipant | null> {
    return this.databaseService.chatParticipant.findFirst({
      where: {
        chatId,
        userId,
      },
    });
  }

  #deleteFileMessageWithFiles(files: MessageFile[]): Promise<void[]> {
    const promises = files.map((file) => this.fileService.deleteFile(file.entityType, file.url));
    return Promise.all(promises);
  }
}
